language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-android-support

notifications:
  email: false

before_install:
 - chmod +x gradlew

script: ./gradlew clean
